# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: External-Scripts/template-machine
    - repository: scriptus
      endpoint: external-script-repo
      type: git
      name: External-Scripts/Criar-Excluir-Maquina


jobs:
- template: python-script-create-vm.yml@templates  # Template reference

