# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: connection
  value: Test-Personal-Uipath # The name of your service connection on Azure DevOps
- name: emailToReceiveResults
  value: yuricamargo4@gmail.com  # The email to send the results of pipeline
- name: FolderName #Name of the folde to publish package
  value: Shared
- name: createProcessBoolean
  value: true



resources:
  repositories:
    - repository: template-script-machine
      type: git
      name: External-Scripts/template-machine
    - repository: template-uipath
      type: git
      name: Projetos/Template-Uipath-Pipeline


jobs:
- job: CreateMachine
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: python-script-create-vm.yml@template-script-machine  # Template reference 
- job: RunWorkflowAnalyzer
  dependsOn: CreateMachine
  condition: succeeded('CreateMachine')
  variables:
    InstanceID: $[ dependencies.CreateMachine.outputs['runScriptThatCreatesMachine.INSTANCE_ID'] ]
  pool: 
    name: Workflow-Analyzer
    demands:
    - agent.name -equals workflow-analyzer-agent-$(InstanceID)
  steps:
  - checkout: self
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $projectPath = "$Env:BUILD_SOURCESDIRECTORY"

        & 'C:\Users\Administrator\AppData\Local\Programs\UiPath\Studio\UiPath.Studio.CommandLine.exe' analyze -p "$projectPath\project.json"
- job: TerminateMachine
  dependsOn:
    - CreateMachine 
    - RunWorkflowAnalyzer
  variables:
    InstanceID: $[ dependencies.CreateMachine.outputs['runScriptThatCreatesMachine.INSTANCE_ID'] ]
  condition: succeeded('RunWorkflowAnalyzer')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: python-script-delete-vm.yml@template-script-machine
# - job: BuildAndPublish
#   steps:
- template: pack-and-publish.yml@template-uipath  # Template reference
  parameters:
    connection: $(connection) # You need to change this with your Orchestrator Connection Name
    vmImage: 'windows-latest' #This image works in most cases, but if you need a Cross Platform Agent, you need to change this
    email: '$(emailToReceiveResults)'
    FolderName: '$(FolderName)'
    createProcessBoolean: '$(createProcessBoolean)'

