# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: External-Scripts/template-machine


jobs:
- job: CreateMachine
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: python-script-create-vm.yml@templates  # Template reference 
- job: RunWorkflowAnalyzer
  dependsOn: CreateMachine
  condition: succeeded('CreateMachine')
  variables:
    InstanceID: $[ dependencies.CreateMachine.outputs['runScriptThatCreatesMachine.INSTANCE_ID'] ]
  pool: 
    name: Workflow-Analyzer
    demands:
    - agent.name -equals workflow-analyzer-agent-$(InstanceID)
  steps:
  - checkout: self
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        & 'C:\Users\Administrator\AppData\Local\Programs\UiPath\Studio\UiPath.Studio.CommandLine.exe' analyze -p "$Env:BUILD_SOURCESDIRECTORY \project.json"
- job: TerminateMachine
  dependsOn: RunWorkflowAnalyzer
  variables:
    InstanceID: $[ dependencies.CreateMachine.outputs['runScriptThatCreatesMachine.INSTANCE_ID'] ]
  condition: succeeded('RunWorkflowAnalyzer')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: python-script-delete-vm.yml@templates
